version: '3.8'

services:
  backend:
    image: yassinsiouda/motivo-server-back:latest
    build: 
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "5002:5002"
      - "8765:8765"
    env_file:
      - .env
    volumes:
      - ./motivo:/app/motivo
      - ./webserver:/app/webserver
      - ./metamotivo-S-1-datasets:/app/metamotivo-S-1-datasets
      - ./storage:/app/storage
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  vibe:
    image: yassinsiouda/cog-vibe:latest
    ports:
      - "5000:5000"
    restart: unless-stopped
    shm_size: '16gb'  # Shared memory size
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    image: yassinsiouda/motivo-client-front:latest
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    env_file:
      - .env
    restart: unless-stopped

