version: '3.8'

services:
  backend:
    image: yassinsiouda/motivo-server-back:latest
    build: 
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "5002:5002"
      - "8765:8765"
    env_file:
      - .env
    volumes:
      - ./motivo:/app/motivo
      - ./webserver:/app/webserver
      - ./storage:/app/storage
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/data
    environment:
      - SQLITE_DATABASE=/data/db.db
    restart: unless-stopped
  
  # vibe:
  #   image: yassinsiouda/cog-vibe:latest
  #   ports:
  #     - "5000:5000"
  #   restart: unless-stopped
  #   shm_size: '16gb'  # Shared memory size
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  
  # backup:
  #     image: yassinsiouda/motivo-backup:latest
  #     build: 
  #       context: ./backup
  #     volumes:
  #       - ./storage:/backup/storage
  #     environment:
  #       - S3_ENDPOINT=${S3_ENDPOINT}
  #       - S3_ACCESS_KEY=${S3_ACCESS_KEY}
  #       - S3_SECRET_KEY=${S3_SECRET_KEY}
  #       - BACKUP_BUCKET=${BACKUP_BUCKET}
  #       - BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS}
  #     restart: unless-stopped

  frontend:
    image: yassinsiouda/motivo-client-front:latest
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    env_file:
      - .env
    restart: unless-stopped

