name: Docker Compose CI CD

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.back
        push: true
        tags: yassinsiouda/motivo-server-back:latest

    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.front
        push: true
        tags: yassinsiouda/motivo-client-front:latest
